let
    Source = Sql.Database("scctsr44\sqlsystems", "servicedesk_db", [Query="SELECT #(lf)    ""wo"".""WORKORDERID"" AS ""Request ID"", #(lf)    ""mdd"".""MODENAME"" AS ""Request Mode"", #(lf)    ""ti"".""FIRST_NAME"" AS ""Technician"", #(lf)    ""cd"".""CATEGORYNAME"" AS ""Category"", #(lf)    ""cri"".""FIRST_NAME"" AS ""Created By"", #(lf)    ""dpt"".""DEPTNAME"" AS ""Department"", #(lf)    ""wotodesc"".""FULLDESCRIPTION"" AS ""Description"", #(lf)    ""qd"".""QUEUENAME"" AS ""Group"", #(lf)    ""aau"".""FIRST_NAME"" AS ""Requester"", #(lf)    ""wo"".""TITLE"" AS ""Subject"", #(lf)    ""wos"".""ASSIGNEDTIME"" AS ""Assigned Time"", #(lf)    ""serdef"".""NAME"" AS ""Service Category"", #(lf)    ""wo"".""CREATEDTIME"" AS ""Created Time"", #(lf)    ""wo"".""COMPLETEDTIME"" AS ""Completed Time""#(lf)FROM ""WorkOrder"" ""wo""#(lf)LEFT JOIN ""ModeDefinition"" ""mdd"" ON ""wo"".""MODEID"" = ""mdd"".""MODEID""#(lf)LEFT JOIN ""SDUser"" ""sdu"" ON ""wo"".""REQUESTERID"" = ""sdu"".""USERID""#(lf)LEFT JOIN ""AaaUser"" ""aau"" ON ""sdu"".""USERID"" = ""aau"".""USER_ID""#(lf)LEFT JOIN ""DepartmentDefinition"" ""dpt"" ON ""wo"".""DEPTID"" = ""dpt"".""DEPTID""#(lf)LEFT JOIN ""WorkOrderStates"" ""wos"" ON ""wo"".""WORKORDERID"" = ""wos"".""WORKORDERID""#(lf)LEFT JOIN ""CategoryDefinition"" ""cd"" ON ""wos"".""CATEGORYID"" = ""cd"".""CATEGORYID""#(lf)LEFT JOIN ""SDUser"" ""td"" ON ""wos"".""OWNERID"" = ""td"".""USERID""#(lf)LEFT JOIN ""AaaUser"" ""ti"" ON ""td"".""USERID"" = ""ti"".""USER_ID""#(lf)LEFT JOIN ""StatusDefinition"" ""std"" ON ""wos"".""STATUSID"" = ""std"".""STATUSID""#(lf)LEFT JOIN ""WorkOrder_Queue"" ""woq"" ON ""wo"".""WORKORDERID"" = ""woq"".""WORKORDERID""#(lf)LEFT JOIN ""QueueDefinition"" ""qd"" ON ""woq"".""QUEUEID"" = ""qd"".""QUEUEID""#(lf)LEFT JOIN ""SDUser"" ""crd"" ON ""wo"".""CREATEDBYID"" = ""crd"".""USERID""#(lf)LEFT JOIN ""AaaUser"" ""cri"" ON ""crd"".""USERID"" = ""cri"".""USER_ID""#(lf)LEFT JOIN ""WorkOrderToDescription"" ""wotodesc"" ON ""wo"".""WORKORDERID"" = ""wotodesc"".""WORKORDERID""#(lf)LEFT JOIN ""ServiceDefinition"" ""serdef"" ON ""wo"".""SERVICEID"" = ""serdef"".""SERVICEID""#(lf)WHERE #(lf)    (#(lf)        (#(lf)            (""qd"".""QUEUENAME"" = N'IFS' OR ""qd"".""QUEUENAME"" = N'IFS Group' OR ""qd"".""QUEUENAME"" =N'Information Security' OR ""qd"".""QUEUENAME""=N'Infrastructure' OR ""qd"".""QUEUENAME""=N'Infrastructure Group' OR ""qd"".""QUEUENAME"" = N'IT-DB' OR ""qd"".""QUEUENAME""=N'IT-Development' OR ""qd"".""QUEUENAME""=N'IT-Support' OR ""qd"".""QUEUENAME""=N'IT-Systems' OR ""qd"".""QUEUENAME"" = N'IT-Systems Group'OR ""qd"".""QUEUENAME"" = N'IT-TOS'OR ""qd"".""QUEUENAME"" = N'Mobile Service'OR ""qd"".""QUEUENAME"" = N'Pending Accounts'OR ""qd"".""QUEUENAME"" = N'Physical Security'OR ""qd"".""QUEUENAME"" = N'Printing Service'OR ""qd"".""QUEUENAME"" = N'SCCT- IT Staff') AND #(lf)            ""std"".""STATUSNAME"" = N'Closed'#(lf)        ) #(lf)        AND #(lf)        (#(lf)            (#(lf)                ""wo"".""CREATEDTIME"" >= 1735689600000 AND  -- Start of 2024 (2024-01-01 00:00:00)#(lf)                ""wo"".""CREATEDTIME"" <= 1830297599000 AND  -- End of 2027 (2027-12-31 23:59:59)#(lf)                ""wo"".""CREATEDTIME"" != 0 AND #(lf)                ""wo"".""CREATEDTIME"" IS NOT NULL AND #(lf)                ""wo"".""CREATEDTIME"" != -1#(lf)            )#(lf)        )#(lf)    ) #(lf)    AND ""wo"".""ISPARENT"" = '1';#(lf)"]),
    #"Removed Columns" = Table.RemoveColumns(Source,{"Description"}),
    #"Added Custom" = Table.AddColumn(#"Removed Columns", "CreatedTime", each #datetime(1970, 1, 1, 0, 0, 0) + #duration(0, 0, 0, [Created Time] / 1000)),
    #"Changed Type with Locale" = Table.TransformColumnTypes(#"Added Custom", {{"CreatedTime", type datetime}}, "en-US"),
    #"Added Custom1" = Table.AddColumn(#"Changed Type with Locale", "CompletedTime", each #datetime(1970, 1, 1, 0, 0, 0) + #duration(0, 0, 0, [Completed Time] / 1000)),
    #"Changed Type" = Table.TransformColumnTypes(#"Added Custom1",{{"CompletedTime", type datetime}}),
    #"Removed Columns1" = Table.RemoveColumns(#"Changed Type",{"Created Time", "Completed Time"})
in
    #"Removed Columns1"
